name: nerfstudio
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.11.4=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - annotated-types==0.7.0
      - anyio==4.5.2
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.4
      - attrs==25.3.0
      - av==12.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - backports-zoneinfo==0.2.1
      - beautifulsoup4==4.14.2
      - bidict==0.23.1
      - bleach==6.1.0
      - blinker==1.8.2
      - cachetools==5.5.2
      - certifi==2025.11.12
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorlog==6.10.1
      - comet-ml==3.54.1
      - comm==0.2.3
      - configargparse==1.7.1
      - configobj==5.0.9
      - contourpy==1.1.1
      - cryptography==46.0.3
      - cycler==0.12.1
      - dash==3.3.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - dill==0.4.0
      - docstring-parser==0.17.0
      - dulwich==0.22.4
      - embreex==2.17.7.post7
      - eval-type-backport==0.3.0
      - everett==3.1.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.16.1
      - fire==0.7.1
      - flask==3.0.3
      - fonttools==4.57.0
      - fpsample==1.0.0
      - fqdn==1.5.1
      - fsspec==2025.3.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - gsplat==1.4.0
      - h11==0.16.0
      - h5py==3.11.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.2.19
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - lxml==6.0.2
      - manifold3d==3.3.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.4
      - mistune==3.1.4
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgpack-numpy==0.4.8
      - msgspec==0.18.6
      - multiprocess==0.70.18
      - narwhals==1.42.1
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nerfacc==0.5.2
      - nerfstudio==1.1.5
      - nest-asyncio==1.6.0
      - networkx==3.1
      - ninja==1.13.0
      - nodeenv==1.9.1
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numpy==1.24.4
      - nuscenes-devkit==1.1.9
      - oauthlib==3.3.1
      - open3d==0.19.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.10.0.84
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathos==0.3.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pip==25.0.1
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.5.0
      - plyfile==1.0.3
      - pox==0.3.6
      - ppft==1.7.7
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycocotools==2.0.7
      - pycollada==0.9
      - pycparser==2.23
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.2
      - pyliblzfse==0.4.1
      - pymeshlab==2023.12.post2
      - pyngrok==7.2.12
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - python-engineio==4.12.3
      - python-json-logger==4.0.0
      - python-socketio==5.15.0
      - pytorch-msssim==1.0.0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - rawpy==0.21.0
      - referencing==0.35.1
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.2.0
      - rpds-py==0.20.1
      - rsa==4.9.1
      - rtree==1.3.0
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentry-sdk==2.45.0
      - shapely==2.0.7
      - shtab==1.7.2
      - simple-websocket==1.1.0
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - splines==0.3.0
      - stack-data==0.6.3
      - svg-path==7.0
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorly==0.9.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.6.7
      - tinycss2==1.2.1
      - tinycudann==2.0
      - tomli==2.3.0
      - torch==2.1.2+cu118
      - torch-fidelity==0.3.0
      - torchmetrics==1.5.2
      - torchvision==0.16.2+cu118
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==4.9.0
      - triton==2.1.0
      - typeguard==4.4.0
      - typing-extensions==4.13.2
      - tyro==0.9.35
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - viser==0.2.7
      - wandb==0.23.0
      - wcwidth==0.2.14
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==13.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - wsproto==1.2.0
      - wurlitzer==3.1.1
      - xatlas==0.0.11
      - xxhash==3.6.0
      - yourdfpy==0.0.58
      - zipp==3.20.2
prefix: /home/john/anaconda3/envs/nerfstudio
